language: ruby
rvm:
  - 2.0.0
bundler_args: --without development production assets

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database devpoint_labs_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
addons:
  code_climate:
